<a href="https://colab.research.google.com/github/aishadeltio13/PYTHON_NIVEL0/blob/main/C3_apuntes_GC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install numpy #instalamos la libreria

In [6]:
import numpy as np #importamos la libreria
print("Ejercicio 1")
a = np.array([1,2,3])
print(a)
# acceso a los elementos
print(a[0])
print(a[-1])
print(a[-2])

# array 2d
print("Ejercicio 2")
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b[0,1])

# operaciones matematicas
print("Ejercicio 3")
arr = np.array([1, 2, 3, 4])
print(arr + 10) # a cada elemento
print(arr * 2)
print("Ejercicio 4")
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2) # elemento a elemento
print(arr1 * arr2)

# Practica
print("Practica")
array = np.array([1, 2, 3])
print(f"La suma de todos sus elementos es {sum(array)}")

Ejercicio 1
[1 2 3]
1
3
2
Ejercicio 2
[[1 2 3]
 [4 5 6]]
2
Ejercicio 3
[11 12 13 14]
[2 4 6 8]
Ejercicio 4
[5 7 9]
[ 4 10 18]
Practica
La suma de todos sus elementos es 6


In [12]:
%pip install requests


In [11]:
import requests
print("Ejercicio 1")
url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url) # nos da la informacion
data = response.json() # convertimos los datos en una lista python (es como una traduccion)
print("posts:", data)
print("posts:", data[0]["title"])

print("Practica")
url2= "https://randomuser.me/api"
response2= requests.get(url)
data2 = response2.json()
print(f"Tipo de respuesto Json : {type(data2)}")

try:
  for a in data2:
    user_id = a["userId"]
    post_id = a["id"]
    title = a["title"]
    print(f"User {user_id} - Post {post_id}: {title}")
except:
  print("Error")





Practica
Tipo de respuesto Json : <class 'list'>
User 1 - Post 1: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
User 1 - Post 2: qui est esse
User 1 - Post 3: ea molestias quasi exercitationem repellat qui ipsa sit aut
User 1 - Post 4: eum et est occaecati
User 1 - Post 5: nesciunt quas odio
User 1 - Post 6: dolorem eum magni eos aperiam quia
User 1 - Post 7: magnam facilis autem
User 1 - Post 8: dolorem dolore est ipsam
User 1 - Post 9: nesciunt iure omnis dolorem tempora et accusantium
User 1 - Post 10: optio molestias id quia eum
User 2 - Post 11: et ea vero quia laudantium autem
User 2 - Post 12: in quibusdam tempore odit est dolorem
User 2 - Post 13: dolorum ut in voluptas mollitia et saepe quo animi
User 2 - Post 14: voluptatem eligendi optio
User 2 - Post 15: eveniet quod temporibus
User 2 - Post 16: sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
User 2 - Post 17: fugit voluptas sed molestias voluptatem provident
User 2 - Post 18